name: Dependabot auto-approve

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Dependabot PR metadata
        id: dependabot
        uses: dependabot/fetch-metadata@v2.4.0

      - name: Enable auto-merge
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          gh pr merge --auto --rebase "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
