name: Dependabot auto-approve

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Rebase branch
        run: |
          git fetch origin
          git rebase origin/main || git rebase --abort
          
      - name: Merge branch
        if: success()
        run: |
          git push origin HEAD:main